# Generated by Django 5.1.5 on 2025-02-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_spectaculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectaculation',
            options={'verbose_name': 'مشخصات کالا', 'verbose_name_plural': 'مشخصات کالا ها'},
        ),
    ]
