# Generated by Django 5.1.5 on 2025-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image610',
            new_name='image10',
        ),
    ]
