# Generated by Django 5.1.5 on 2025-02-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_image1_remove_product_image10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'عکس های محصولات'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image9',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
