# Generated by Django 5.1.5 on 2025-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_productimage_options_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IA', 'Is Available'), ('UA', 'Unavailable')], default='UA', max_length=2, verbose_name='موجودِی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(verbose_name='قیمت'),
        ),
    ]
