# Generated by Django 5.1.5 on 2025-02-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_status_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IA', 'Is Available'), ('UA', 'Unavailable')], default='UA', max_length=2, verbose_name='موجودی'),
        ),
    ]
