# Generated by Django 5.1.5 on 2025-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_subcategory_image_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(),
        ),
    ]
