# Generated by Django 5.1.5 on 2025-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
    ]
