# Generated by Django 5.1.5 on 2025-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], default='ناموجود', max_length=10, verbose_name='موجودی'),
        ),
    ]
