# Generated by Django 5.1.5 on 2025-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], default='ناموجود', max_length=10, verbose_name='وضعیت'),
        ),
    ]
