# Generated by Django 5.1.5 on 2025-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_product_discount_price_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('unavailabe', 'ناموجود')], default='unavailabe', max_length=10, verbose_name='وضعیت'),
        ),
    ]
