# Generated by Django 5.1.5 on 2025-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.BigIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
