# Generated by Django 5.1.5 on 2025-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
