# Generated by Django 5.1.5 on 2025-02-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_product_discount_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_expiry',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_expiray',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انقضای تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount_active',
            field=models.BooleanField(default=False, verbose_name='فعال؟'),
        ),
    ]
