# Generated by Django 5.1.5 on 2025-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speculation',
            name='text',
            field=models.TextField(),
        ),
    ]
