# Generated by Django 5.1.5 on 2025-03-05 09:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_speculation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speculation',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
