# Generated by Django 5.1.5 on 2025-03-24 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
