# Generated by Django 5.1.5 on 2025-03-24 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_user_article_author_article_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
