# Generated by Django 5.1.5 on 2025-03-24 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articleimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='ArticleImages',
            new_name='PostImages',
        ),
    ]
