# Generated by Django 5.1.5 on 2025-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'زیر دسته بندی مقاله',
                'verbose_name_plural': 'زیر دسته بندی های مقاله ها',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True),
        ),
    ]
