# Generated by Django 5.1.5 on 2025-02-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'ادرس فروشگاه', 'verbose_name_plural': 'ادرس فروشگاه'},
        ),
    ]
