# Generated by Django 5.1.5 on 2025-03-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_alter_address_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='ShopAddress',
        ),
    ]
